version: '3.8'
services:
  meister-bot:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: meister-bot-prod:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    restart: unless-stopped
